### ISSUE TITLE
사이트별 크롤링 이슈

### ISSUE THREAD

**Issue by g1-tommy** [cyber-security-capstone-21-1/monitor-assistant#23]

**Comment by g1-tommy** [comment]
일부 사이트 크롤링 시도 시 500 에러.
특정 칼럼 반환 시 Not Null 영역 필드에 Null 반환 원인 추정.

**Comment by junghyun2ee** [comment]
루리웹 --> 로컬에서도 작동안함 / url로 접속을 못하는것같음--> 한글 인코딩 문제일듯

**Comment by g1-tommy** [comment]
FMKorea

**Comment by junghyun2ee** [comment]
보배드림 / 로컬에서도 문제 --> post 방식으로 보내는게 애매함

**Comment by junghyun2ee** [comment]
일베 --> 될때가 있고 안될때가 있음 / 로컬에선 맨날 됨

**Comment by junghyun2ee** [comment]
오늘의 유머 --> 로컬에선 작동 잘되는데, ec2에서는 성공메세지 출력하는데 아무것도 못가져옴

**Comment by junghyun2ee** [comment]
클리앙 --> 로컬에서 정상 작동 / ec2에선 504error

**Comment by junghyun2ee** [comment]
1. 인증서 문제 ?

CS 3 (보배드림 ) 
Error: Remote host terminated the handshake

2. 로컬에서 작동 잘되는데 서버에 올리면 안되는 사이트

CS 4 (클리앙) : 504
CS 11(루리웹) :  502
CS16(인벤)  : 502
CS 17 (82cook) :  502

3.  robots.txt로 아예 차단해버리는 사이트 

CS 5(디씨)
CS12 (에펨) 

4. Data 빈 상태로 반환하는데, Status 200인 사이트
 
CS18 (웃긴대학)
CS07 (오늘의 유머)
